### ISSUE TITLE
Add robustness to the “Edit storefront/volunteer time” pages

### ISSUE THREAD

**Issue by pcshah1996** [GTBitsOfGood/irc#24]
* Allow the ability to clear changes
* Secondary popup confirm button when submitting new changes

**Comment by Sukhmai** [comment]
I started to work on this, plus I'm fixing some bugs with the Storefront/Volunteer Time pages themselves.

**Comment by Sukhmai** [comment]
The reset button functionality now works, and both the save and reset button have confirm buttons.
